// Scan src/sources/*.js and regenerate src/feeds.js so that dropping a new
// source file into src/sources/ is enough to register it.
import { readdirSync, writeFileSync, readFileSync } from "node:fs";
import { join, basename } from "node:path";

const sourcesDir = join(import.meta.dirname, "..", "src", "sources");
const files = readdirSync(sourcesDir)
  .filter((f) => f.endsWith(".js") && !f.startsWith("_"))
  .sort();

const ident = (f) => basename(f, ".js").replace(/[^a-zA-Z0-9_$]/g, "_");

const code =
  `// Auto-generated by scripts/gen-feeds.js — do not edit by hand.\n` +
  files
    .map((f) => `import s_${ident(f)} from "./sources/${f}";`)
    .join("\n") +
  `\n\nexport const SOURCES = [\n` +
  files.map((f) => `  s_${ident(f)},`).join("\n") +
  `\n];\n\nexport const findSource = (slug) => SOURCES.find((s) => s.slug === slug);\n`;

const feedsPath = join(sourcesDir, "..", "feeds.js");
if (readFileSync(feedsPath, "utf8") !== code) {
  writeFileSync(feedsPath, code);
  console.log(`gen-feeds: registered ${files.length} source(s): ${files.join(", ")}`);
}
