// Auto-generated by scripts/gen-feeds.js — do not edit by hand.
import s_epoch_ai from "./sources/epoch-ai.js";
import s_zgtsshzy from "./sources/zgtsshzy.js";

export const SOURCES = [
  s_epoch_ai,
  s_zgtsshzy,
];

export const findSource = (slug) => SOURCES.find((s) => s.slug === slug);
